# Configuration for the release-drafter action
# See docs here: https://github.com/marketplace/actions/release-drafter
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'New Features'
    label: '⭐ goal: addition'
  - title: 'Improvements'
    label: '✨ goal: improvement'
  - title: 'Bug Fixes'
    label: '🛠 goal: fix'
# Exclude dependabot PRs from release notes
exclude-labels:
  - 'dependencies'
change-template: '- $TITLE: #$NUMBER by @$AUTHOR'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES

  ## Credits

  Special thanks to $CONTRIBUTORS for their contributions!

  ## See an issue?

  Does anything look wrong in this release? Please [report a bug](https://github.com/creativecommons/vocabulary/issues/new?labels=bug%2C+awaiting+triage&template=bug_report.md).
