# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: CC Vocabulary
# All technologies used
technologies: Sass, Webpack, Storybook, Bulma
# Whether this repository should be featured on the CC Open Source site
featured: true
# Slack channel name
slack: 'cc-dev-vocabulary'
