/**
 * Create an HTMLElement with the given tag, class and children.
 *
 * This function is a convenience function to provide a declarative interface
 * for generating DOM inside JavaScript.
 *
 * The extremely terse name `h` comes from Vue.js.
 *
 * @param {string} tagName - the name of the HTML tag for the element
 * @param {Array} classes - a list of classes to apply to the element
 * @param {Array} children - an Array of DOM nodes to place inside the element
 * @param {function} callbackFn - a function for performing actions on the node
 * @return {HTMLElement} the element generated by the function
 */
export const h = (tagName, classes = [], children = [], callbackFn = null) => {
  const element = document.createElement(tagName)
  if (classes) {
    element.classList.add(...classes)
  }
  if (children) {
    children.forEach(child => element.appendChild(child))
  }
  if (callbackFn) {
    callbackFn(element)
  }
  return element
}
