name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your first issue here! Be sure to follow the issue template! The notify email will be sent to you as soon as.'
        pr-message: 'Thanks for your first Pull-request here! Be sure to follow the issue template! The notify email will be sent to you as soon as.'
        
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Comment to post on an individual's first issue
        issue-message: Thanks for your first issue here! Be sure to follow the issue template! The notify email will be sent to you as soon as.
        # Comment to post on an individual's first pull request
        pr-message: Thanks for your first Pull-request here! Be sure to follow the issue template! The notify email will be sent to you as soon as.
