on: pull_request
name: Pull Request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Test Pull Requests
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/creativecommons/projects/13
        GITHUB_PROJECT_COLUMN_NAME: "Tested"

